### ISSUE TITLE
Zooming to buffer instead of the route (when searching by location) 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/configurable-locator#168]
When using: Search By Location (you will get a buffer )
Instead of Zooming to the extent of the route, please zoom to the extent of the buffer. 

Do not implement for this functionality: Search For Activity (no buffer) 

Related to #166

**Comment by lindsayking** [comment]
@LindsayThomas 

"If a buffer is executed as part of the application logic, please zoom to the extent of the buffer."
* With v1.5, the app now zooms to the buffer rather than the route, but the buffer is partially obscured by the legend and/or the bottom panel.

"if a buffer does not exist and a route does, please zoom to the full extent of the route."
* With v1.5 the app zooms to the route, but depending on the route, it may be partially obscured by the legend and/or the bottom panel.  This is particularly the case for routes that have more of a North-South direction than an East-West direction.
