### ISSUE TITLE
Words interrupted due to word wrapping in popup and bottom panel

### ISSUE THREAD

**Issue by lindsayking** [Esri/configurable-locator#188]
@CTLocalGovTeam 

Word wrapping in the popup and bottom panel is happening mid-word and is resulting in interrupted words, making the text difficult to read.  This is the case with standard attribute-list popups as well as custom popups.

The image below provides a comparison between the [released version (left)](http://tryitlive.arcgis.com/wateraccesslocator/) and the [latest code drop (v1.5, right)](http://50.18.115.76/wateraccesslocatorsg1.5/).  This issue was introduced at the latest code drop, and we suspect is related to https://github.com/Esri/configurable-locator/issues/164.

![image](https://cloud.githubusercontent.com/assets/4316336/9092678/6385115a-3b5c-11e5-885a-f1c87266a6ec.png)

What would be involved in fixing this issue?

FYI, this is the issue @LindsayThomas mentioned in our call today.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Just wanted to highlight that this is happening in the pop-up as well as the carousel.

**Comment by lindsayking** [comment]
@CTLocalGovTeam  Any thoughts on this issue?

**Comment by CTLocalGovTeam** [comment]
@lindsayking @LindsayThomas 

The latest code drop contains word wrapping at the character level instead of at word level. We did this to accomodate large pieces of text in either field names or values for e.g., see screenshot below when set to wrap at the word level. 

![popuplong](https://cloud.githubusercontent.com/assets/2959186/9131615/cea61a88-3d0a-11e5-8e94-a3c0368a9721.jpg)

We can either do wrapping by characters or wrapping by words. We have observed that ArcGIS Online popups wrap only by words.

If we wrap by words, then popup will display a horizontal scrollbar as shown below. Please let us know if this is ok.

![popup](https://cloud.githubusercontent.com/assets/2959186/9131688/7680a76e-3d0b-11e5-840c-0cc56deee940.jpg)

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Please proceed with this approach.  When ready, please submit a pull request on top of the v1.5 pull request you submitted at the end of July.

**Comment by lindsayking** [comment]
This issue is fixed with v1.5.1.  Tested with standard and custom popups.
